name = "image-card-maker"
main = "index.js"
compatibility_date = "2024-01-01"

[build]
upload.format = "modules"
upload.rules = [
  { type = "ESModule", globs = ["**/*.js"] }
]

[build.upload]
format = "modules"
dir = "."

[vars]
# Add any environment variables here if needed
# POPCAT_API_KEY = "your_key_here"

[dev]
ip = "0.0.0.0"
port = 8787
